name: process
version: 2.3.0
versioned_at: 2026-10-07 13:31
description: Specification-driven development process rules.
entrypoint: README.md
dependencies:
  - name: meta
    version: 1.6.0
    constraint: compatible
