name: process
version: 4.0.0
versioned_at: 2026-10-08 17:44
description: Specification-driven development process rules.
entrypoint: README.md
dependencies:
- name: meta
  version: 2.0.2
  constraint: compatible
